### ISSUE TITLE
Overlap between nodes is too big

### ISSUE THREAD

**Issue by fjruizruano** [maickrau/GraphAligner#45]
Hi,

I am trying to map 4 ONT reads against a graph generated with hifiasm with this command:
`$ GraphAligner -g hifiasm.hic.p_utg.gfa -f nanopore_4reads.fastq -a map.gaf -x vg`

However, I stops after few seconds with this message:

```
GraphAligner Branch master commit 02c8e2628bba16425dc58cdf67199319f0a7a304 2021-04-23 09:06:36 -0400
GraphAligner Branch master commit 02c8e2628bba16425dc58cdf67199319f0a7a304 2021-04-23 09:06:36 -0400
Load graph from hifiasm.hic.p_utg.gfa
Error in the graph: Overlap between nodes utg011657l and utg010083l is too big. Fix the overlap to be smaller than both nodes
Error in the graph: Overlap between nodes utg011657l and utg010083l is too big. Fix the overlap to be smaller than both nodes
```

Any help to solve this issue?

Thanks in advance,
Francisco.

**Comment by maickrau** [comment]
Hi, this happens when there is an edge between two nodes with an overlap that is as big (or bigger than) one of the nodes, so the graph is not valid. You can find the lengths of the nodes with:

`grep -P '^S\tutg011657l\t' < hifiasm.hic.p_utg.gfa | cut -f 3 | wc -c`
`grep -P '^S\tutg010083l\t' < hifiasm.hic.p_utg.gfa | cut -f 3 | wc -c`

and the overlap with:

`grep -P '^L' < hifiasm.hic.p_utg.gfa | grep -P '\tutg010083l\t' | grep -P '\tutg011657l\t'`

The overlap (sixth column) should be smaller than both nodes. You can try to manually fix the edge overlap to be smaller than both nodes (eg. one less than the smaller node). This might bias the alignment slightly in that region.

**Comment by fjruizruano** [comment]
Thanks a lot! I will try it.
Best.

**Comment by maickrau** [comment]
Could you share the graph?

**Comment by vpymerel** [comment]
@dcopetti if you find/found a solution, I am also trying to use graphaligner on hifiasm output and encountering similar porblems ...

**Comment by dcopetti** [comment]
Hello all,
Apologies I had to focus on other projects.
After hearing the feedback on this and #81, I will go for the Verkko option, as suggested.
