### ISSUE TITLE
Are the “name” field and "node_id" field reversed?

### ISSUE THREAD

**Issue by tanger-code** [maickrau/GraphAligner#88]
![image](https://github.com/maickrau/GraphAligner/assets/74750242/494824ac-2979-4ae0-9054-b5a5319abf10)

I use GraphAligner to align some long reads to a gfa graph. But in the gam file, it looks like the `name` area and the `node_id` area are reversed. As shown in the picture above, the  `"node_id": "676997"`  is not in the graph, but the` "name": "43503065"` is in the graph.

**Comment by maickrau** [comment]
The `name` and `node_id` should be same unless the graph has any non-numeric node IDs (`.gam` format only supports integer `node_id`), could you upload the graph?

**Comment by tanger-code** [comment]
https://s3-us-west-2.amazonaws.com/human-pangenomics/pangenomes/freeze/freeze1/minigraph-cactus/hprc-v1.1-mc-grch38/hprc-v1.1-mc-grch38.chroms/chr21.vg
This is the original graph, and I use `vg convert` to convert it to `gfa` format.

**Comment by tanger-code** [comment]
vg version v1.44.0 "Solara"
command: `vg convert chr21.vg -f -t 48 > chr21.gfa`

**Comment by maickrau** [comment]
Could you also tell the exact GraphAligner command and the output of `GraphAligner --version`?

**Comment by maickrau** [comment]
I got the bug to reproduce in 1.0.17. This is fixed in version 1.0.17b and you can update by specifying the version in conda: `conda install graphaligner=1.0.17b`. Currently the bioconda versioning is a bit messed up because by default conda selects the older 1.0.17 instead of the newer 1.0.17b, so if you don't specify the version it installs an older version instead of the newest.

**Comment by tanger-code** [comment]
Thank you, it works well now.
